export const INVOICE_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const INVOICE_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const INVOICE_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const INVOICE_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const INVOICE_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const INVOICE_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const INVOICE_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const INVOICE_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const INVOICE_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const INVOICE_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const INVOICE_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const INVOICE_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'

export const INVOICE_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const INVOICE_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const INVOICE_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
